shim-version: v0.3.2@sha256:2bbbf67720a258f8fb92a470f2368215b97fa5ee92afa117d376e776e34e2373
cvm-version: 0.5.10
cpus: 8
memory: 16384

containers:
  - name: "random-logger"
    image: ""
    args: [
      "chentex/random-logger:v1.0.1"
    ]

shim:
  listen-port: 443
  upstream-port: 3000
  publish-attestation: true
  tls-challenge: dns
