shim-version: v0.3.18@sha256:7d9f98be78c91ede89f43c948a12d084fae34312effe9395ca7ed572991cb561
cvm-version: 0.5.15
cpus: 4
memory: 16384

containers:
  - name: "random-logger"
    image: "chentex/random-logger:v1.0.1"
    args: []

  - name: "alloy"
    image: ""
    args: [
      "-v", "/var/run/docker.sock:/var/run/docker.sock",
      "ghcr.io/tinfoilsh/alloy-collector:0.0.2"
    ]

shim:
  listen-port: 443
  upstream-port: 3000
